// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNrwGGoI65llhiX3AoSlFIskik4XYPaI',
    appId: '1:1013290130046:web:1191b68bee11daf801162f',
    messagingSenderId: '1013290130046',
    projectId: 'clickconnect-dec54',
    authDomain: 'clickconnect-dec54.firebaseapp.com',
    storageBucket: 'clickconnect-dec54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChiyySWWQMB8eABpgIUOPa5Ts3-Mha-T4',
    appId: '1:1013290130046:android:41be5e95158c2c7001162f',
    messagingSenderId: '1013290130046',
    projectId: 'clickconnect-dec54',
    storageBucket: 'clickconnect-dec54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yPBgwaUXUXoxHuWyeP0w1yQSuHn6Y2Q',
    appId: '1:1013290130046:ios:2c088fa7d1b4304f01162f',
    messagingSenderId: '1013290130046',
    projectId: 'clickconnect-dec54',
    storageBucket: 'clickconnect-dec54.firebasestorage.app',
    iosBundleId: 'com.example.clickConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0yPBgwaUXUXoxHuWyeP0w1yQSuHn6Y2Q',
    appId: '1:1013290130046:ios:2c088fa7d1b4304f01162f',
    messagingSenderId: '1013290130046',
    projectId: 'clickconnect-dec54',
    storageBucket: 'clickconnect-dec54.firebasestorage.app',
    iosBundleId: 'com.example.clickConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDNrwGGoI65llhiX3AoSlFIskik4XYPaI',
    appId: '1:1013290130046:web:1634e52e67788b1501162f',
    messagingSenderId: '1013290130046',
    projectId: 'clickconnect-dec54',
    authDomain: 'clickconnect-dec54.firebaseapp.com',
    storageBucket: 'clickconnect-dec54.firebasestorage.app',
  );
}
